### PR TITLE
Add password reset functionality and password expiry check

### PR DESCRIPTION
**Pull request by AdelAlghamdi1**
## Description

[Describe the change that was made in this PR]

### Todos

- [x] Tested and working locally
- [x] Code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] Code changes documented
- [x] Requested review from >= 1 devs on the team

### How to test
I have tested all via postman
[Add detailed steps to test the changes that have been made]

### Screenshots and/or Gifs

[Insert screenshots and/or gifs showing the graphic representation of the change]

### Associated MS Planner Tasks

- [create email reset password ](https://planner.cloud.microsoft/deakin365.onmicrosoft.com/Home/Task/IKMF5GnoCUes7TC7r4f2I8gAB5pi?Type=TaskLink&Channel=Link&CreatedTime=638623317668830000)

### Known Issues
the issue that we do not have a reset password now and user need to reset their password I have create endpoints to allow the user to reset their password

### CODE REVIEW

**Review by AsherAli22 — APPROVED** [review]

**Comment by AsherAli22** [comment]
LGTM

**Review by HamzaTahir22 — APPROVED** [review]

**Comment by HamzaTahir22** [comment]
@AdelAlghamdi1 can we merge this?

**Comment by HamzaTahir22** [comment]
@AdelAlghamdi1   Lets merge this. Shall we?

**Review by Onwa1kenobi — CHANGES_REQUESTED** [review]
Please fill out the PR template @AdelAlghamdi1.

**Comment by HamzaTahir22** [comment]
We are short of time so merging the PR.

@AdelAlghamdi1 you can edit the PR Template and add the missing details

**Review by HamzaTahir22 — APPROVED** [review]

**Comment by AdelAlghamdi1** [comment]
Hey for this PR I will close as @Onwa1kenobi  has done it

**Pull request closed without merging**
